In [1]:
import tensorflow as tf

In [3]:
import numpy as np

1、利用tf.constant生成张量，第一个参数是张量里的具体内容，第二个参数是张量的数据类型。  
看张量是几维的，数shape里的逗号，逗号隔开了几个数字，这个张量就是几维的。然后看每个数字大小，这个数字有多大，说明在这一维度有多少元素。

In [2]:
a = tf.constant([1, 5], dtype = tf.int64)
print(a)
print(a.dtype)
print(a.shape)

tf.Tensor([1 5], shape=(2,), dtype=int64)
<dtype: 'int64'>
(2,)


2、可以通过tf.convert_to_tensor将numpy格式的数据转换成tensor。  
格式：tf.convert_to_tensor(数据名， 数据类型)

In [6]:
a = np.arange(0, 5)
b = tf.convert_to_tensor(a, dtype=tf.int64)
print(a)
print(b)

[0 1 2 3 4]
tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int64)


3、tf.zeros(维度)，用于创建元素都是0的张量。  
tf.ones(dim)，用于创建元素都是1的张量  
tf.fill(维度，想要填充的值)，用于创建指定维度、填充指定值的张量  
维度在填写的时候，如果是一维的，直接写；  
如果是多维的，用中括号[]括起来，然后每个维度之间用逗号隔开。

In [8]:
c = tf.zeros([3, 4])
d = tf.ones([4, 5])
e = tf.fill([2, 2], 6)
print(c, d, e)

tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(3, 4), dtype=float32) tf.Tensor(
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]], shape=(4, 5), dtype=float32) tf.Tensor(
[[6 6]
 [6 6]], shape=(2, 2), dtype=int32)


4、如何随机生成数据，使得生成的数据服从正态分布？  
tf.random.normal(维度，mean=均值，stddev=标准差)，这样生成的随机值满足指定的正太分布。  
tf.random.truncated_normal(维度，mean=均值，stddev=标准差），这样的正态分布随机值落在正负两个标准差之内。

In [9]:
f = tf.random.normal([2,3], mean=0.5, stddev=1)
g = tf.random.truncated_normal([2,3], mean=0.5, stddev=1)
print(f)
print(g)

tf.Tensor(
[[1.0238166 0.5016341 0.9328464]
 [0.5213056 1.745805  0.2926699]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[ 0.31841895  0.28715572 -0.761616  ]
 [ 0.6590975  -0.22640288 -0.62056744]], shape=(2, 3), dtype=float32)


5、如何生成均匀分布的随机数据？  
tf.random.uniform(维度，minval=最小值，maxval=最大值），生成在[minval, maxval)范围内的均匀分布随机数。注意是左闭右开区间！

In [10]:
h = tf.random.uniform([2,3], minval=1, maxval=2)
print(h)

tf.Tensor(
[[1.8615977 1.4800426 1.5563991]
 [1.0055131 1.6682237 1.1136595]], shape=(2, 3), dtype=float32)
