In [2]:
import tensorflow as tf
import numpy as np

1、如何进行张量类型的转换？  
使用tf.cast(张量名，dtype=想要转换为的类型）

In [3]:
a = tf.constant([1., 2., 3.], dtype=tf.float32)
print(a)
b = tf.cast(a, dtype=tf.int64)
print(b)

tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
tf.Tensor([1 2 3], shape=(3,), dtype=int64)


2、如何找到一个张量中指定维度上的最大值或者最小值？  
tf.reduce_min(张量名），求最小值  
tf.reduce_max(张量名），求最大值

In [4]:
print(tf.reduce_min(b))
print(tf.reduce_max(b))

tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)


3、什么是axis？
axis用于指定操作的维度。例如，axis=0表示对张量的第一个维度进行操作（跨行），axis=2表示对张量的第二个维度进行操作（跨列）。

4、如何在指定维度上对张量求和或者求平均值？  
tf.reduce_mean(张量名，axis=要进行操作的维度），对执行维度求平均值。  
tf.reduce_sum（张量名，axis=要进行操作的维度）。对指定维度求和。  
如果不填写axis那就是对所有维度进行操作。

In [5]:
c = tf.constant([[2,3,4],[3,6,9]], dtype=tf.int64)
print(c)
d = tf.reduce_mean(c, axis = 0)
e = tf.reduce_sum(c, axis = 1)
print(d)
print(e)

tf.Tensor(
[[2 3 4]
 [3 6 9]], shape=(2, 3), dtype=int64)
tf.Tensor([2 4 6], shape=(3,), dtype=int64)
tf.Tensor([ 9 18], shape=(2,), dtype=int64)


5、如何将变量标记为可训练？
tf.Variable(初始值）将变量标记为可训练。

In [6]:
tf.Variable(tf.random.normal([2,2], mean=0.5, stddev=1))

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 0.73563  ,  0.6767465],
       [ 1.8069587, -0.8069413]], dtype=float32)>

6、如何对张量做四则运算？加减乘除
tf.add  
tf.subtract  
tf.mutiply  
tf.devide  

7、如何对张量平方、指定次数运算、开方？  
tf.square  
tf.pow  
tf.sqrt

8、如何做矩阵乘法？  
tf.matmul(矩阵1，矩阵2)  

In [7]:
f = tf.fill([3,2], 3)
g = tf.fill([2,3], 4)
h = tf.matmul(f, g)
print(h)

tf.Tensor(
[[24 24 24]
 [24 24 24]
 [24 24 24]], shape=(3, 3), dtype=int32)


9、如何将特征和标签进行配对？  
tf.data.Dataset.from_tensor_slices((特征，标签))

In [11]:
i = tf.constant([1, 2, 3], dtype=tf.int32)
labels = tf.constant([0, 1, 0], dtype=tf.int32)
dataset = tf.data.Dataset.from_tensor_slices((i, labels))
print(dataset)
for data in dataset:
    print(data)

<TensorSliceDataset shapes: ((), ()), types: (tf.int32, tf.int32)>
(<tf.Tensor: shape=(), dtype=int32, numpy=1>, <tf.Tensor: shape=(), dtype=int32, numpy=0>)
(<tf.Tensor: shape=(), dtype=int32, numpy=2>, <tf.Tensor: shape=(), dtype=int32, numpy=1>)
(<tf.Tensor: shape=(), dtype=int32, numpy=3>, <tf.Tensor: shape=(), dtype=int32, numpy=0>)


10、如何进行梯度计算？  
with结构记录计算过程，gradient求出张量梯度。  
with tf.GradientTape as tape:  
  若干个计算过程  
grad = tape.gradient(损失函数，要对那个变量求导）

In [14]:
with tf.GradientTape() as tape:
    x = tf.Variable(tf.constant(3.0))
    y = tf.pow(x, 2)
grad = tape.gradient(y, x)
print(grad)

tf.Tensor(6.0, shape=(), dtype=float32)


11、enumerate如何使用？  
enumerate用于遍历每一个元素并且将其和索引号组合。组合后的形式为：索引 元素

In [16]:
j = tf.constant([1,2,3])
for i, element in enumerate(j):
    print (i, element)

0 tf.Tensor(1, shape=(), dtype=int32)
1 tf.Tensor(2, shape=(), dtype=int32)
2 tf.Tensor(3, shape=(), dtype=int32)


12、如何将标签转换为独热码表示？
tf.one_hot(待转换数据，depth=几分类）  

In [18]:
labels = tf.constant([0,1,2])
classes = 3
output = tf.one_hot(labels, depth=classes)
print(output)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


13、如何让输出符合概率分布？  
tf.nn.softmax(输出变量)  
![](1-45-1.png)
![](1-45-2.png)

In [19]:
y = tf.constant([1.12, 2.33, -0.567])
y_pro = tf.nn.softmax(y)
print(y_pro)

tf.Tensor([0.22033429 0.7388876  0.04077813], shape=(3,), dtype=float32)


14、如何进行自减更新？  
首先必须要将变量标记为可训练。  
w.assign_sub(自减值)

In [20]:
w = tf.Variable(tf.constant(7))
w.assign_sub(1)
print(w)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=6>


15、如何返回张量沿指定方向最大值的索引？  
tf.argmax(张量，axis=操作的方向)

In [21]:
m = tf.constant([[1,2,3],[4,5,6],[7,1,3]])
n = tf.argmax(m, axis = 0)
p = tf.argmax(m, axis = 1)
print(n)
print(p)

tf.Tensor([2 1 1], shape=(3,), dtype=int64)
tf.Tensor([2 2 0], shape=(3,), dtype=int64)
